# Generated by Django 4.1.5 on 2023-03-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_note_order_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='additional_info',
            new_name='company',
        ),
    ]
